# Generated by Django 6.1.1 on 2026-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Eletrica', 'Elétrica'), ('Hidraulica', 'Hidráulica'), ('Mobiliario', 'Mobiliário'), ('Limpeza', 'Limpeza'), ('Equipamento', 'Equipamento'), ('Outro', 'Outro')], max_length=30)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Média'), ('Alta', 'Alta')], max_length=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em analise', 'Em análise'), ('Resolvido', 'Resolvido')], default='Pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
