# Generated by Django 6.1.1 on 2026-10-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ocorrencias/'),
        ),
    ]
