# Generated by Django 6.1.1 on 2026-10-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_ocorrencia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='foto',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
